fos_elastica:
    clients:
        default: { host: localhost, port: 9200,  logger: false}

    indexes:
        ulost:
                    client: default
                    settings:
                                    index:
                                        analysis:
                                            analyzer:
                                                custom_search_analyzer:
                                                    type: custom
                                                    tokenizer: standard
                                                    filter   : [standard, lowercase, asciifolding]
                                                custom_index_analyzer:
                                                    type: custom
                                                    tokenizer: standard
                                                    filter   : [standard, lowercase, asciifolding, custom_filter]
                                            filter:
                                                custom_filter:
                                                    type: edgeNGram
                                                    side: front
                                                    min_gram: 1
                                                    max_gram: 20
                    types:
                        region:
                            mappings:
                              name : ~
                            persistence:
                                driver: orm
                                model: Ulost\VilleBundle\Entity\Region
                                provider:
                                      batch_size: 100
                        ville:
                            mappings:
                              name : {search_analyzer: custom_search_analyzer, index_analyzer: custom_index_analyzer, type: string}
                              codePostal : { type: string }
                              id : {type: string}
                            persistence:
                                driver: orm
                                model: Ulost\VilleBundle\Entity\Ville
                                provider:
                                     batch_size: 100

