# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512
        Ulost\UserBundle\Entity\User : sha512

    role_hierarchy:
        ROLE_USER:        ROLE_ANONYMOUS
        ROLE_VILLE:       ROLE_USER
        ROLE_ADMIN:       [ROLE_USER, ROLE_VILLE]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_VILLE, ROLE_ALLOWED_TO_SWITCH]
    providers:
          fos_userbundle:
                   id: fos_user.user_provider.username_email

    firewalls:

          main:
                   pattern: ^/
                   form_login:
                       provider: fos_userbundle
                       csrf_token_generator: security.csrf.token_manager
                       login_path: /user/login
                       failure_path: /user/login
                       always_use_default_target_path: false
                       default_target_path: /home
                       success_handler: redirect.after.login

                   logout:
                      target: /home
                   anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/profil/, role: ROLE_USER }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/object/, role: ROLE_ADMIN }
        - { path: ^/municipale/, role: ROLE_VILLE}

