# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
 security.exception_listener.class: Ulost\CoreBundle\Security\Firewall\ExceptionListener
services:

    ulost.js_vars:
      class: stdClass


    ulost.form.registration:
        class: Ulost\UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: ulost_user_registration }

    ulost.annonce_voter:
            class: Ulost\AnnonceBundle\Security\AnnonceVoter
            arguments: ['@security.access.decision_manager']
            tags:
                - { name: security.voter }
            # small performance boost
            public: false


    ulost.correspondance_voter:
            class: Ulost\CorrespondanceBundle\Security\CorrespondanceVoter
            arguments: ['@security.access.decision_manager']
            tags:
                - { name: security.voter }
            # small performance boost
            public: false


    redirect.after.login:
        class: Ulost\UserBundle\Redirection\AfterLoginRedirection
        arguments: [@router]