<?php

namespace Ulost\CoreBundle\Repository;

/**
 * CategoryObjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryObjetRepository extends \Doctrine\ORM\EntityRepository
{
}
