<?php

namespace Ulost\CoreBundle\Repository;

/**
 * CategoryFAQRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryFAQRepository extends \Doctrine\ORM\EntityRepository
{
}
