<?php

namespace Ulost\CoreBundle\Entity;

/**
 * ObjetQuestionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjetQuestionsRepository extends \Doctrine\ORM\EntityRepository
{
}
