<?php

namespace Ulost\VilleBundle\Repository;

/**
 * regionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends \Doctrine\ORM\EntityRepository
{
}
