<?php

namespace Ulost\VilleBundle\Repository;

/**
 * AgglomerationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VilleServiceRelationRepository extends \Doctrine\ORM\EntityRepository
{
}
