<?php

namespace Ulost\MunicipaleBundle\Repository;
use Ulost\MunicipaleBundle\Entity\Service;

/**
 * StockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmplacementRepository extends \Doctrine\ORM\EntityRepository
{

    public function findEmplacementsPrincipaux(Service $service){

            $query = $this->createQueryBuilder('a');

            $query
                ->where('a.service = :service')
                ->setParameter('service',$service)
                ->andWhere('a.parent IS NULL')
            ;
            return $query
                ->getQuery()
               ;
        }


}
