<?php

namespace Ulost\MunicipaleBundle\Repository;


use Ulost\VilleBundle\Entity\Ville;

/**
 * StockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends \Doctrine\ORM\EntityRepository
{
public function getServiceFromVille(Ville $ville){
    $query = $this->getEntityManager()->createQueryBuilder('s')
        ->add('select', 's, v, vR')
        ->add('from', 'UlostMunicipaleBundle:Service s')
        ->leftJoin('s.villeServiceRelations', 'vR')
        ->leftJoin('vR.ville', 'v')
        ->andWhere('v = :ville')
        ->setParameter('ville',$ville);
    return $query;
}

}
