<?php

namespace Ulost\AnnonceBundle\Repository;

use Ulost\AnnonceBundle\Entity\Annonce;
use Ulost\ObjectBundle\Entity\Question;

/**
 * ReponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReponseRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByAnnonceAndQuestion(Annonce $annonce, Question $question)
    {

        $query = $this->createQueryBuilder('r');

        $query->where('r.annonce = :annonce')
            ->setParameter('annonce', $annonce)
            ->andWhere('r.question= :question')
            ->setParameter('question', $question);
        return $query
            ->getQuery()
            ->getOneOrNullResult();
    }
}
